AbcSize:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

