Lint/RescueWithoutErrorClass:
  Exclude:
    - 'lib/reagan/changeset.rb'

Metrics/AbcSize:
  Max: 41

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 147

Metrics/MethodLength:
  Max: 28

Metrics/PerceivedComplexity:
  Max: 12

Style/GuardClause:
  Exclude:
    - 'lib/reagan.rb'
    - 'lib/reagan/config.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'lib/reagan/test_reagan.rb'
